name: ADM monitor
on:
  schedule:
    - cron: "0 8 * * *"
    - cron: "0 10 * * *"
    - cron: "0 12 * * *"  # ≈ 14:00 Europe/Rome (in ora legale, UTC+2)
    - cron: "0 14 * * *"
    - cron: "0 16 * * *"
    - cron: "0 18 * * *"
  workflow_dispatch:      # pulsante "Run workflow"

permissions:
  contents: write

concurrency:
  group: adm-monitor
  cancel-in-progress: false

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install requests beautifulsoup4

      - name: Run monitor
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID:   ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python monitor.py

      - name: Commit state (if changed)
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain state/adm_state.json || true)" ]; then
            git add state/adm_state.json
            git commit -m "Update ADM monitor state [skip ci]" || echo "Nothing to commit"
            git push
          else
            echo "No changes in adm_state.json"
          fi

      - name: Write heartbeat (always)
        run: |
          mkdir -p state
          date -u +"%Y-%m-%dT%H:%M:%SZ" > state/last_run_utc.txt

      - name: Commit heartbeat
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add state/last_run_utc.txt
          git commit -m "Heartbeat: update last run [skip ci]" || echo "Nothing to commit"
          git push
